vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 Jun 2002 08:38:07 -0000
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|distrib/ltxl.asp
vti_nexttolasttimemodified:TR|06 Jun 2002 08:38:07 -0000
vti_author:SR|XAND-WEB3\\bermuda
vti_syncwith_localhost\\c\:\\my documents\\webs\\vescom\\usa/c\:/my documents/webs/vescom/usa:TR|06 Jun 2002 08:38:07 -0000
vti_version:SW|5.0.2.2623
vti_modifiedby:SR|XAND-WEB3\\vesconite
vti_timecreated:TR|08 Aug 2003 14:05:11 -0000
vti_syncwith_216.150.141.101\:858:TR|06 Jun 2002 08:38:07 -0000
vti_filesize:IR|5124
vti_syncwith_www.vesconite.com\:80:TR|06 Jun 2002 08:38:07 -0000
vti_syncwith_localhost\\c\:\\documents and settings\\joan marran\\my documents\\webs\\vescom\\usa/c\:/documents and settings/joan marran/my documents/webs/vescom/usa:TR|06 Jun 2002 08:38:07 -0000
vti_cacheddtm:TX|26 May 2005 10:06:45 -0000
