<%
' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.
On Error Resume Next

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("Database2_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "main", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(14)
	Dim arFormDBFields0(14)
	Dim arFormValues0(14)

	arFormFields0(0) = "VS04"
	arFormDBFields0(0) = "VS04"
	arFormValues0(0) = Request("VS04")
	arFormFields0(1) = "HW03"
	arFormDBFields0(1) = "HW03"
	arFormValues0(1) = Request("HW03")
	arFormFields0(2) = "size"
	arFormDBFields0(2) = "size"
	arFormValues0(2) = Request("size")
	arFormFields0(3) = "price"
	arFormDBFields0(3) = "price"
	arFormValues0(3) = Request("price")
	arFormFields0(4) = "descrip"
	arFormDBFields0(4) = "descrip"
	arFormValues0(4) = Request("descrip")
	arFormFields0(5) = "unit"
	arFormDBFields0(5) = "unit"
	arFormValues0(5) = Request("unit")
	arFormFields0(6) = "stockitem"
	arFormDBFields0(6) = "stockitem"
	arFormValues0(6) = Request("stockitem")
	arFormFields0(7) = "weight"
	arFormDBFields0(7) = "weight"
	arFormValues0(7) = Request("weight")
	arFormFields0(8) = "IN05"
	arFormDBFields0(8) = "IN05"
	arFormValues0(8) = Request("IN05")
	arFormFields0(9) = "vga"
	arFormDBFields0(9) = "Vga"
	arFormValues0(9) = Request("vga")
	arFormFields0(10) = "ST40"
	arFormDBFields0(10) = "ST40"
	arFormValues0(10) = Request("ST40")
	arFormFields0(11) = "IE02"
	arFormDBFields0(11) = "IE02"
	arFormValues0(11) = Request("IE02")
	arFormFields0(12) = "jhb"
	arFormDBFields0(12) = "Jhb"
	arFormValues0(12) = Request("jhb")
	arFormFields0(13) = "cat"
	arFormDBFields0(13) = "cat"
	arFormValues0(13) = Request("cat")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0


	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	FP_FormConfirmation "text/html; charset=windows-1252",_
						"Form Confirmation",_
						"Thank you for submitting the following information:",_
						"dbf_update.asp",_
						"Return to the form."

End If
End If

%>
<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Database update</title>
<meta name="Microsoft Border" content="b">
</head>

<body stylesrc="default.html" topmargin="0" bgcolor="#F9FBFF"><!--msnavigation--><table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><!--msnavigation--><td valign="top">

<p>&nbsp;</p>
<p><b><font face="Arial" color="#000086">Add / Edit records.&nbsp; Database 
ves0001</font></b></p>
<form method="POST" action="dbf_update.asp" onSubmit="" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" SuggestedExt="asp" S-DataConnection="Database2" S-RecordSource="main" U-Database-URL="_borders/fpdb/ves0001.mdb" S-Form-Fields="VS04 HW03 size price descrip unit stockitem weight IN05 vga ST40 IE02 jhb cat" S-Form-DBFields="VS04 HW03 size price descrip unit stockitem weight IN05 Vga ST40 IE02 Jhb cat" U-ASP-Include-Url="_fpclass/fpdbform.inc" startspan --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="_fpclass/fpdbform.inc"--><!--webbot bot="SaveDatabase" i-checksum="40548" endspan --><table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
    <tr>
      <td width="16%" bgcolor="#E6CCFF"><font face="Arial">Stock item</font></td>
      <td width="12%" bgcolor="#E6CCFF">
      <input type="text" name="stockitem" size="15" tabindex="1"></td>
      <td width="5%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="16%" bgcolor="#E6CCFF"><font face="Arial">Description</font></td>
      <td width="51%" colspan="2" bgcolor="#E6CCFF">
      <input type="text" name="descrip" size="30" tabindex="2"></td>
    </tr>
    <tr>
      <td width="16%" bgcolor="#E6CCFF"><font face="Arial">Category</font></td>
      <td width="12%" bgcolor="#E6CCFF">
      <input type="text" name="cat" size="2" tabindex="3"></td>
      <td width="5%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="16%" bgcolor="#E6CCFF"><font face="Arial">Unit</font></td>
      <td width="34%" bgcolor="#E6CCFF">
      <input type="text" name="unit" size="4" tabindex="4"></td>
      <td width="17%" bgcolor="#E6CCFF">&nbsp;</td>
    </tr>
    <tr>
      <td width="15%" bgcolor="#E6CCFF"><font face="Arial">Price</font></td>
      <td width="24%" bgcolor="#E6CCFF">
      <input type="text" name="price" size="10" tabindex="5"></td>
      <td width="5%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="16%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="34%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="17%" bgcolor="#E6CCFF">&nbsp;</td>
    </tr>
    <tr>
      <td width="15%" bgcolor="#E6CCFF"><font face="Arial">Weight</font></td>
      <td width="24%" bgcolor="#E6CCFF">
      <input type="text" name="weight" size="10"></td>
      <td width="5%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="16%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="34%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="17%" bgcolor="#E6CCFF">&nbsp;</td>
    </tr>
    <tr>
      <td width="15%" bgcolor="#E6CCFF"><font face="Arial">Size</font></td>
      <td width="24%" bgcolor="#E6CCFF">
      <input type="text" name="size" size="10"></td>
      <td width="5%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="16%" bgcolor="#E6CCFF">&nbsp;</td>
      <td width="51%" colspan="2" bgcolor="#E6CCFF">&nbsp;</td>
    </tr>
  </table>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
    <tr>
      <td width="16%">&nbsp;</td>
      <td width="10%">&nbsp;</td>
      <td width="7%">&nbsp;</td>
      <td width="12%">&nbsp;</td>
      <td width="14%">&nbsp;</td>
      <td width="13%">&nbsp;</td>
      <td width="10%">&nbsp;</td>
      <td width="31%">&nbsp;</td>
    </tr>
    <tr>
      <td width="16%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      Stock status</font></b></td>
      <td width="10%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      Jhb</font></b></td>
      <td width="7%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">Vga</font></b></td>
      <td width="12%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      Intertech</font></b></td>
      <td width="14%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      Inter<br>
      Empress</font></b></td>
      <td width="13%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      Smart<br>
      Trading</font></b></td>
      <td width="10%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      Hydo<br>
      Watt</font></b></td>
      <td width="31%" bgcolor="#E8FFE8"><b><font face="Arial" color="#000086">
      SEA</font></b></td>
    </tr>
    <tr>
      <td width="14%" bgcolor="#E8FFE8">&nbsp;</td>
      <td width="8%" bgcolor="#E8FFE8"><input type="text" name="jhb" size="3"></td>
      <td width="13%" bgcolor="#E8FFE8"><input type="text" name="vga" size="3"></td>
      <td width="12%" bgcolor="#E8FFE8"><input type="text" name="IN05" size="3"></td>
      <td width="14%" bgcolor="#E8FFE8"><input type="text" name="IE02" size="3"></td>
      <td width="13%" bgcolor="#E8FFE8"><input type="text" name="ST40" size="3"></td>
      <td width="10%" bgcolor="#E8FFE8"><input type="text" name="HW03" size="3"></td>
      <td width="31%" bgcolor="#E8FFE8"><input type="text" name="VS04" size="3"></td>
    </tr>
  </table>
  <p><input type="submit" value="Submit" name="B1"><input type="reset" value="Reset" name="B2"></p>
</form>
<p>&nbsp;</p>
<p><font face="Arial" size="2">Updated Mar 22 2002</font></p>

<!--msnavigation--></td></tr><!--msnavigation--></table><!--msnavigation--><table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td>

  <div align="center">
    <center>
  <table border="0" cellspacing="0" cellpadding="2" width="703" style="border-collapse: collapse" bordercolor="#111111">
    <tr>
    <td width="711" height="1" colspan="3" align="center">
        <font face="Arial" size="2"><font color="#000000">
        For </font><font color="#FF0000">information and quotes,</font><font color="#000000"> 
        e-mail </font><a href="mailto:vesconite@vesconite.com">
        vesconite@vesconite.com</a></font>
        <br>
        <font face="Arial" size="2"><font color="#FF0000">Feedback</font> is 
        appreciated.
        <a href="mailto:vesconite@vesconite.com?subject=Feedback to the WEBMASTER">
        e-mail the webmaster</a></font></td>
    </tr>
    <tr>
    <td width="691" height="1" colspan="3">
        <p align="center"><font face="Arial" size="2">
      <a href="http://www.vesconite.com/">Home</a><font color="#000080">&nbsp;
        | &nbsp;</font><a href="http://www.vesconite.com/vesco/contact.htm">Contact us</a> &nbsp;<font color="#000080">
        |</font>&nbsp; <a href="http://www.vesconite.com/vesco/site.htm">Site map</a>&nbsp;<font color="#000080">
        |&nbsp; <a href="http://www.vesconite.com/vesco/site_search.htm">Search</a>&nbsp;
        |&nbsp;&nbsp;</font><a href="http://www.vesconite.com/enquiry.htm">Enquiry
        form</a><font color="#000080">&nbsp;&nbsp; |&nbsp;
      <a href="http://www.vesconite.com/footer_links/copyright.htm">Copyright</a>&nbsp;
        |&nbsp; <a href="http://www.vesconite.com/footer_links/privacy.htm">Privacy</a></font><br>
      &nbsp; <span style="background-color: #FFFFFF" lang="en-za">
        <a href="mall/PassageWay/All%202011.asp">Stock Finder</a></span></font><font color="#000080" face="Arial" size="2">
        &nbsp;|&nbsp;
    <a href="mall/lobby.asp">Dealer Update</a>&nbsp; | &nbsp;<a href="mall/LTXL_nokia.asp">Mobile</a></font><font face="Arial" size="2">&nbsp; 
      |&nbsp;
      <a href="mall/stff/export/exp_login.asp">Export</a><span lang="en-za">&nbsp; 
        |&nbsp;&nbsp;
        <a href="https://vescosales.com/wstore/">Webstore</a></span></font></td>
    </tr>
    <tr>
    <td width="323" height="1" valign="top">
        <font face="Arial" color="#FF0000" size="2">
        <span style="letter-spacing: -1pt"><b>Toll free/Linea gratuita</b></span></font><font face="Arial" color="#000080" size="2"><b><br>
        Australia </b>
        </font>
          <font face="Arial" color="#000086" size="2">1800 
        833 448</font><font face="Arial" size="2" color="#000080"><b><br>
        Brasil</b> </font><strong style="font-weight: 400">
        <font face="Arial" color="#000080" size="2">0800 891 87 16</font></strong><font face="Arial" color="#000080" size="2"><b><br>
        Canada</b> 1 866 682 3484<br>
        <b>Chile</b> </font><font face="Arial" size="2" color="#000086">(2) 570 
        3855<br>
        </font><font face="Arial" color="#000080" size="2">
        <b>Germany</b> 0443 1892 3899</font><font face="Arial" size="2" color="#000086"><br>
        </font><font face="Arial" size="2" color="#000080"><b>Hong Kong</b> </font>
        <font face="Arial" size="2" color="#000086">800 930 211</font><font face="Arial" size="2" color="#000080"><br>
        </font><span class="443554203-21102008"><b>
        <font size="2" face="Arial" color="#000080">Ireland </font></b></span>
        <font face="Arial" size="2" color="#000080">1800 552 711</font><span class="443554203-21102008"><font size="2" face="Arial" color="#000080"><b><br>
        Netherlands&nbsp;</b></font></span><font face="Arial" size="2" color="#000080">08000 223 805<b><br>
        New Zealand</b> 0800 450 878<b><br>
        Portugal</b> 800 827 007<br>
        </font>
          <font face="Arial" size="2" color="#000086">
          <b>UAE</b> 800 027 01 03</font><font face="Arial" size="2" color="#000080"><br>
        <b>
        UK </b>0800 731 9745 / 020 3239 9044<b><br>
        USA</b> (7-3EST) 1 866 635 75 96 / (713) 574-7255</font></td>
    <td width="1" height="1" valign="top">
    <font size="2" face="Arial">
    <br>
&nbsp;</font></td>
    <td width="299" height="1" valign="top">
        <b><font color="#FF0000" size="2" face="Arial">Fax</font></b><font face="Arial" color="#000080" size="2"><b><br>
        Australia </b><strong style="font-weight: 400">+61 386 485 671</strong></font><b><font face="Arial" size="2" color="#000080"><br>
        <br>
        Canada
        </font></b><font face="Arial" color="#000080" size="2">
        (416) 352 15 27<b><br>
        </b><strong style="font-weight: 400"><br>
        </strong><br>
        &nbsp;</font><p>&nbsp;</p>
        <p><font face="Arial" color="#000080" size="2">
        <br>
        <b>UK</b> 0207 681 3444<b><br>
        USA</b> (212) 937 3184</font></td>
    </tr>
    <tr>
    <td width="699" colspan="3" height="1" valign="top">
    <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
      <tr>
        <td width="12%"><a href="http://www.vesconite.com/"><img border="0" src="_borders/VSalesLogo.gif" width="67" height="30" alt="Vesconite Manufacturer: Home Page"></a></td>
        <td width="88%">
        <p align="center"><font size="2" face="Arial">©</font><span style="FONT-FAMILY: Arial, Helvetica, sans-serif; FONT-SIZE: 12px" class="Apple-style-span">2012 
        Vesco Plastics Sales, Pty Ltd. All rights reserved. Content of this site 
        may not be copied or redistributed without the express written consent 
        of Vesco Plastics Sales, Pty Ltd.</span><font size="2" face="Arial">&nbsp;
    <a href="http://www.vesconite.com/footer_links/warranty.htm">Warranty 
        disclaimer</a></font></td>
      </tr>
    </table>
    </td>
    </tr>
    <tr>
    <td width="699" colspan="3" height="1" valign="top">
    <p align="center"></td>
    </tr>
  </table>
    </center>
  </div>

    </td></tr><!--msnavigation--></table></body>

</html>