vti_encoding:SR|utf8-nl
vti_author:SR|XAND-WEB3\\vesconite
vti_timelastmodified:TR|08 Aug 2003 05:53:20 -0000
vti_modifiedby:SR|XAND-WEB3\\vesconite
vti_timecreated:TR|03 Sep 2003 13:21:37 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.7802
vti_syncwith_localhost\\c\:\\my documents\\webs\\vescom\\exp/c\:/my documents/webs/vescom/exp:TR|08 Aug 2003 05:53:20 -0000
vti_cacheddtm:TX|03 Sep 2003 13:21:37 -0000
vti_filesize:IR|5124
