<%
' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.
On Error Resume Next

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("Database2_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "parts", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(2)
	Dim arFormDBFields0(2)
	Dim arFormValues0(2)

	arFormFields0(0) = "pic"
	arFormDBFields0(0) = "pic"
	arFormValues0(0) = Request("pic")
	arFormFields0(1) = "OEMn"
	arFormDBFields0(1) = "OEMn"
	arFormValues0(1) = Request("OEMn")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0


	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	FP_FormConfirmation "text/html; charset=windows-1252",_
						"Form Confirmation",_
						"Thank you for submitting the following information:",_
						"ASPsample.asp",_
						"Return to the form."

End If
End If

%>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Part Finder pic display</title>
</head>

<body stylesrc="../../../Index.htm" bgcolor="#F2F7FF">

<p>&nbsp;</p>
<form method="POST" action="ASPsample.asp" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" SuggestedExt="asp" U-ASP-Include-Url="../../../_fpclass/fpdbform.inc" S-DataConnection="Database2" S-RecordSource="parts" U-Database-URL="../../../fpdb/parts.mdb" S-Form-Fields="pic OEMn" S-Form-DBFields="pic OEMn" startspan --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../../../_fpclass/fpdbform.inc"--><!--webbot bot="SaveDatabase" i-checksum="52631" endspan --><p>
  OEMn<input type="text" name="OEMn" size="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <input type="text" name="pic" size="20"><input type="submit" value="Submit" name="B1"><input type="reset" value="Reset" name="B2"></p>
</form>
<p>&nbsp;</p>
<p>&nbsp;</p>

</body>

</html>