vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|18 Jul 2002 06:48:12 -0000
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|mall/stff/parts/aspsample.asp dbf_update.asp
vti_filesize:IR|4167
vti_nexttolasttimemodified:TR|17 May 2002 10:30:30 -0000
vti_syncwith_localhost\\c\:\\my documents\\webs\\vescoza2 with subs\\inter/c\:/my documents/webs/vescoza2 with subs/inter:TR|17 May 2002 10:30:30 -0000
vti_syncwith_www.vesconite.com\:80/shop:TR|17 May 2002 10:30:30 -0000
vti_author:SR|XAND-WEB3\\bermuda
vti_syncwith_www.vesconite.co.za\:80/inter:TR|17 May 2002 10:30:30 -0000
vti_modifiedby:SR|XAND-WEB3\\vesconite
vti_timecreated:TR|08 Aug 2003 14:10:03 -0000
vti_syncwith_216.150.141.101\:858/stock:TR|17 May 2002 10:30:30 -0000
vti_syncwith_www.vesconite.com\:80/stock:TR|18 Jul 2002 06:48:12 -0000
vti_syncwith_localhost\\c\:\\documents and settings\\joan marran\\my documents\\webs\\vescom\\stock/c\:/documents and settings/joan marran/my documents/webs/vescom/stock:TR|18 Jul 2002 06:48:12 -0000
vti_cacheddtm:TX|26 May 2005 07:55:47 -0000
