vti_encoding:SR|utf8-nl
vti_author:SR|XAND-WEB3\\vesconite
vti_syncwith_www.vesconite.com\:80/export:TR|08 Aug 2003 05:53:20 -0000
vti_timelastmodified:TR|08 Aug 2003 05:53:20 -0000
vti_modifiedby:SR|XAND-WEB3\\vesconite
vti_timecreated:TR|08 Mar 2006 13:45:34 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.7802
vti_syncwith_localhost\\c\:\\documents and settings\\joan marran\\my documents\\webs\\vescom\\miami/c\:/documents and settings/joan marran/my documents/webs/vescom/miami:TR|08 Aug 2003 05:53:20 -0000
vti_cacheddtm:TX|08 Mar 2006 13:45:34 -0000
vti_filesize:IR|8217
