vti_encoding:SR|utf8-nl
vti_author:SR|XAND-WEB3\\vesconite
vti_version:SW|5.0.2.2623
vti_timelastmodified:TR|06 Aug 2003 08:51:39 -0000
vti_modifiedby:SR|XAND-WEB3\\vesconite
vti_timecreated:TR|03 Sep 2003 13:45:11 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.7802
vti_syncwith_localhost\\c\:\\my documents\\webs\\vescom\\staff/c\:/my documents/webs/vescom/staff:TR|06 Aug 2003 08:51:39 -0000
vti_cacheddtm:TX|03 Sep 2003 13:45:11 -0000
vti_filesize:IR|2054
