vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Jun 2003 06:24:40 -0000
vti_extenderversion:SR|4.0.2.7802
vti_filesize:IR|2054
vti_nexttolasttimemodified:TR|11 Jun 2003 06:18:20 -0000
vti_version:SW|5.0.2.2623
vti_syncwith_localhost\\c\:\\my documents\\webs\\vescom\\distrib/c\:/my documents/webs/vescom/distrib:TR|11 Jun 2003 06:24:40 -0000
vti_author:SR|XAND-WEB3\\bermuda
vti_modifiedby:SR|XAND-WEB3\\bermuda
vti_timecreated:TR|08 Aug 2003 14:09:06 -0000
vti_backlinkinfo:VX|
vti_syncwith_216.150.141.101\:858/distrib:TR|11 Jun 2003 06:24:40 -0000
vti_cacheddtm:TX|11 Jun 2003 06:18:20 -0000
